### PR TITLE
Upgraded pg to latest dependency

### PR DESCRIPTION
**Pull request by AndersMoberg**
Hi,

I've had issues with postgresql-easy (connection to database silently hangs forever), and after some debugging I found that it was due to the pg dependency being out of date.
Upgrading it to 8 resolves the immediate issue we've had.

### Unit tests:
` PASS  ./sql-util.test.js
  sql
    √ constructor (3ms)
    √ deleteAll
    √ deleteById (1ms)
    √ disconnect
    √ getAll
    √ getById (1ms)
    √ insert

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        2s, estimated 6s
Ran all test suites.`

### Questions:
Haven't been able to check this, but on the [website](https://node-postgres.com/) for the pg dependency, versions >=8.2.0 are suitable for node >=14. Should a "engine" value be added to the package.json? Would you like me to do this in this branch before merge? Maybe it makes sense to jump to the next major version for such a change?

Let me know if you disagree, I can investigate 8.1.x version of pg.

### CODE REVIEW

**Review by mvolkmann — APPROVED** [review]

**Comment by mvolkmann** [comment]
Thanks @AndersMoberg!

**Comment by AndersMoberg** [comment]
@mvolkmann, thanks for merging my change!
Would it be possible to publish a new version with this? I'd suggest a minor/major version jump.

**Comment by mvolkmann** [comment]
Sorry, I forgot to do that. I’m out of the county on vacation now. I’ll have to do it when I return on 9/16. R. Mark VolkmannObject Computing, Inc.On Sep 6, 2023, at 3:10 AM, Anders Moberg ***@***.***> wrote:﻿
@mvolkmann, thanks for merging my change!
Would it be possible to publish a new version with this? I'd suggest a minor/major version jump.

**Comment by mvolkmann** [comment]
@AndersMoberg Sorry, I forgot to push a new version when I returned from vacation. I just pushed version 1.3.0 with your changes.

**Pull request merged**
